export enum ESectionIds {
  HOMEPAGE_HOME = 'home-home',
  HOMEPAGE_OFFERS = 'home-offers',
  HOMEPAGE_PERKS = 'home-perks',
  GROUP_WORKOUTS_HOME = 'group-home',
  GROUP_WORKOUTS_MMA = 'group-mma',
  GROUP_WORKOUTS_BJJ = 'group-bjj',
  GROUP_WORKOUTS_BOXING = 'group-boxing',
  GROUP_WORKOUTS_CROSSFIT = 'group-crossfit',
  GROUP_WORKOUTS_SCHEDULE = 'group-schedule',
  LOCATIONS_HOME = 'locations-home',
  LOCATIONS_PL = 'locations-pl',
  LOCATIONS_USA = 'locations-usa',
  LOCATIONS_BR = 'locations-br',
}