export enum ESectionIds {
  HOMEPAGE_HOME = 'home-home',
  HOMEPAGE_OFFERS = 'home-offers',
  HOMEPAGE_PERKS = 'home-perks',
  GROUP_WORKOUTS_HOME = 'group-home',
  GROUP_WORKOUTS_MMA = 'group-mma',
  GROUP_WORKOUTS_BJJ = 'group-bjj',
  GROUP_WORKOUTS_BOXING = 'group-boxing',
  GROUP_WORKOUTS_CROSSFIT = 'group-crossfit',
  GROUP_WORKOUTS_SCHEDULE = 'group-schedule',
  LOCATIONS_HOME = 'locations-home',
  LOCATIONS_PL = 'locations-pl',
  LOCATIONS_USA = 'locations-usa',
  LOCATIONS_BR = 'locations-br',
  LOCATION_PL = 'location-pl',
  LOCATION_USA = 'location-usa',
  LOCATION_BR = 'location-br',
  INDIVIDUAL_PROGRAMS_HOME = 'individual-programs-home',
  INDIVIDUAL_PROGRAMS_MMA = 'individual-programs-mma',
  INDIVIDUAL_PROGRAMS_POWERLIFTING = 'individual-programs-powerlifting',
  INDIVIDUAL_PROGRAMS_STAND_UP = 'individual-programs-stand-up',
  INDIVIDUAL_PROGRAMS_GROUND_GAME = 'individual-programs-ground-game',
  INDIVIDUAL_PROGRAMS_ABOUT = 'individual-programs-about',
  INDIVIDUAL_PROGRAM_HOME = 'individual-program-home',
  INDIVIDUAL_PROGRAM_ABOUT = 'individual-program-about',
  INDIVIDUAL_PROGRAM_COACHES = 'individual-program-coaches',
  CALORIES_CALCULATOR = 'calories-calculator',
}